### ISSUE TITLE
bindata prefix

### ISSUE THREAD

**Issue by willscott** [OpenObservatory/gooni#3]
the bindata command specified in `makefile` will name the data constants with a prefix. an example is:

`bindataDataMigrations1createmsmtresultssqlBytes()`

However the current calls don't use this prefix, and refer to

`dataMigrations1_create_msmt_resultsSqlBytes()`

The `-prefix ''` flag can be used to remove the 'bindata' prefix appended by the makefile variant. i don't see how to re-add the '_'s

More generally though, it seems there may be an issue with stable naming from this library / current process.

**Comment by willscott** [comment]
i suppose worth noting that the actual interface provided by the generated files is stable.

it's just that they aren't going to be identical so each re-generation by different machines / versions of the library will result in re-commits / maybe worth having in .gitignore or find ways to more fully specify the generated output

**Comment by hellais** [comment]
Are you using this go-bindata fork: github.com/shuLhan/go-bindata?

The original go-bindata is abandonware and there are various unresolved bugs.

**Comment by willscott** [comment]
That seems like a great argument for vendoring the specific version of the library we want to include.

**Comment by willscott** [comment]
and yes. I am using the shuLhan version. The version that installed for me was at eb5746d, a few commits past v3.3.0
