### ISSUE TITLE
creation of config is non-obvious

### ISSUE THREAD

**Issue by willscott** [OpenObservatory/gooni#4]
when attempting to run a command
```
$ ooni run ndt
   • Starting ndt             
   ⨯ failed to find a config  
   ⨯ main exit                 error=failed to find a config
```

There is no option in `--help` explaining how to create the config or run the on-boarding process.

**Comment by hellais** [comment]
The on-boarding should run by default if a config is not present. If it doesn't that's a bug. Though keep in mind this is heavily work in progress and many things are very likely broken.

The place to look at to fix this is the https://github.com/OpenObservatory/gooni/blob/master/internal/cli/root/root.go.

You should also maybe enable extra verbosity (`-v`) for debug level information.

**Comment by willscott** [comment]
I'm making progress at fixing bugs, and i think have the initial config and database setup stabilized in my fork http://github.com/willscott/gooni

**Comment by hellais** [comment]
I guess this can now be considered closed.
